[package]
name = "zkevm-circuits"
version = "0.1.0"
authors = ["therealyingtong <yingtong@z.cash>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff = "0.11"
halo2 = { git = "https://github.com/appliedzkp/halo2.git", branch = "feat/optimized-asm", features = ["asm"] }
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256", branch = "introduce-assembly-complete", features = ["asm"] }
bigint = "4"
num = "0.4"
sha3 = "0.7.2"
digest = "0.7.6"
array-init = "2.0.0"
paste = "1.0"
bus-mapping = { path = "../bus-mapping"}
eth-types = { path = "../eth-types" }
serde_json = "1.0.66"
rand_xorshift = "0.3"
rand = "0.8"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "binary_value"
harness = false
