[package]
name = "keccak256"
version = "0.1.0"
edition = "2018"

[features]
dev-graph = ["halo2/dev-graph", "plotters"]

[dependencies]
halo2 = { git = "https://github.com/appliedzkp/halo2.git", branch = "feat/optimized-asm", features = ["asm"] }
itertools = "0.10.1"
num-bigint = "0.4.2"
num-traits = "0.2.14"
pairing = { git = 'https://github.com/appliedzkp/pairing', package = "pairing_bn256", branch = "introduce-assembly-complete", features = ["asm"] }
plotters = { version = "0.3.0", optional = true }

[dev-dependencies]
pretty_assertions = "1.0"
